# Create a Docker image for the Local Neighborhood algorithm here
FROM python:3.15.0b1-alpine3.23

# Set the working directory name
WORKDIR /LocalNeighborhood

# Copy the python file
COPY local_neighborhood_alg.py .
